export default function getNewsCardsData() {
  return [
    {
      Date: '5/1/1991',
      Headline: 'CSDL Begins!',
      Text: 'The Collaborative Software Development Laboratory was founded in the Spring of 1991.',
      URL: '',
      Media: '',
    },
    {
      Date: '5/1/1994',
      Headline: 'CLARE',
      Text: 'Dadong Wan completes Ph.D. research: CLARE: A Computer-Supported Collaborative Learning Environment Based on the Thematic Structure of Scientific Text.',
      URL: 'http://csdl.ics.hawaii.edu/research/clare',
      Media: '',
    },
    {
      Date: '6/1/1995',
      Headline: 'AEN',
      Text: 'Cam Moore completes M.S. research:  Supporting authoring and learning in a strongly collaborative hypertext system: The Annotated Egret Navigator.',
      URL: 'http://csdl.ics.hawaii.edu/research/aen',
      Media: 'images/aen.png',
    },
    {
      Date: '7/1/1995',
      Headline: 'WWW',
      Text: 'Rosemary Andrada Sumajit completes M.S. research:  Building Community through the World Wide Web.',
      URL: '',
      Media: '',
    },
    {
      Date: '8/1/1996',
      Headline: 'CSRS',
      Text: 'Danu Tjahjono completes Ph.D. research: Exploring the effectiveness of formal technical review factors with CSRS, a collaborative software review system.',
      URL: 'http://csdl.ics.hawaii.edu/research/csrs',
      Media: 'images/csrs.gif',
    },
    {
      Date: '5/1/1998',
      Headline: 'JavaWizard',
      Text: 'Jennifer Geis completes M.S. research:  JavaWizard: Investigating Defect Detection and Analysis.',
      URL: 'http://csdl.ics.hawaii.edu/research/jwiz',
      Media: 'images/jwiz.jpg',
    },
    {
      Date: '5/1/1999',
      Headline: 'PSP Data Quality',
      Text: 'Anne Disney completes M.S. research:  Data Quality Problems in the Personal Software Process.',
      URL: 'http://csdl.ics.hawaii.edu/research/psp-data-quality',
      Media: '',
    },
    {
      Date: '12/1/1999',
      Headline: 'LOCC',
      Text: 'Joe Dane completes M.S. research:  Modular Program Size Counting.',
      URL: 'http://csdl.ics.hawaii.edu/research/locc',
      Media: 'images/locc.gif',
    },
    {
      Date: '3/1/2000',
      Headline: 'MCS',
      Text: 'Robert Brewer completes M.S. research:  Improving Mailing List Archives Through Condensation.',
      URL: 'http://csdl.ics.hawaii.edu/research/mcs',
      Media: '',
    },
    {
      Date: '8/1/2000',
      Headline: 'LEAP',
      Text: 'Cam Moore completes Ph.D. research: Investigating Individual Software Development: An Evaluation of the Leap Toolkit.',
      URL: 'http://csdl.ics.hawaii.edu/research/leap',
      Media: 'images/leap.gif',
    },
    {
      Date: '8/1/2000',
      Headline: 'javaJAM',
      Text: 'Monir Hodges completes M.S. research:  JavaJam: Supporting Collaborative Review and Improvement of Open Source Software.',
      URL: 'http://csdl.ics.hawaii.edu/research/javajam',
      Media: 'images/javaJAM.gif',
    },
    {
      Date: '5/1/2001',
      Headline: 'Dolphin Whistles',
      Text: 'Timothy Burgess completes M.S. research:  An artificial neural network for recognition of simulated dolphin whistles.',
      URL: '',
      Media: '',
    },
    {
      Date: '6/1/2001',
      Headline: 'VCommerce',
      Text: 'Mette Moffett completes undergraduate honors thesis:  The Design, Development, and Evaluation of VCommerce: A Virtual Environment to Support Entrepreneurial Learning.',
      URL: 'http://csdl.ics.hawaii.edu/research/vcommerce',
      Media: 'images/VCommerce.jpg',
    },
    {
      Date: '5/1/2002',
      Headline: 'INCA',
      Text: 'Jitender Miglani completes M.S. research:  The design, implementation, and evaluation of INCA: an automated system for approval code allocation.',
      URL: 'http://csdl.ics.hawaii.edu/research/inca',
      Media: '',
    },
    {
      Date: '5/1/2003',
      Headline: 'JBlanket',
      Text: 'Joy Agustin completes M.S. research:  Improving software quality through extreme coverage with JBlanket.',
      URL: 'http://csdl.ics.hawaii.edu/research/jblanket',
      Media: 'images/JBlanket.gif',
    },
    {
      Date: '5/1/2003',
      Headline: 'Hackystat',
      Text: 'Support for fine-grained software development process and product data collection and analysis.',
      URL: 'http://csdl.ics.hawaii.edu/research/hackystat',
      Media: 'images/hackystat.png',
    },
    {
      Date: '5/1/2003',
      Headline: 'CLEW',
      Text: 'Aaron Kagawa completes undergraduate honors thesis:  The design, implementation, and evaluation of CLEW: An improved Collegiate Department Website.',
      URL: '',
      Media: 'images/kagawa.jpeg',
    },
    {
      Date: '5/1/2005',
      Headline: 'SCLC',
      Text: 'Multi-language code counting.',
      URL: 'http://csdl.ics.hawaii.edu/research/sclc',
      Media: 'images/sclc.gif',
    },
    {
      Date: '8/1/2005',
      Headline: 'PRI',
      Text: 'Aaron Kagawa completes M.S. research: Priority Ranked Inspection: Supporting Effective Inspection in Resource-limited Organizations.',
      URL: 'http://csdl.ics.hawaii.edu/research/priority-ranked-inspection',
      Media: 'images/kagawa.jpeg',
    },
    {
      Date: '12/1/2006',
      Headline: 'Software Project Telemetry',
      Text: 'Qin Zhang completes Ph.D. research: Improving Software Development Process and Product Management with Software Project Telemetry.',
      URL: 'http://csdl.ics.hawaii.edu/research/software-project-telemetry',
      Media: 'images/telemetry.png',
    },
    {
      Date: '12/1/2007',
      Headline: 'Zorro',
      Text: 'Hongbing Kou completes Ph.D. research: Automated Inference of Software Development Behaviors: Design, Implementation and Validation of Zorro for Test-Driven Development.',
      URL: 'http://csdl.ics.hawaii.edu/research/zorro',
      Media: 'images/zorro.png',
    },
    {
      Date: '5/1/2008',
      Headline: 'Jupiter',
      Text: 'Takuya Yamashita completes M.S. research:  Evaluation of Jupiter: A Lightweight Code Review Framework.',
      URL: 'http://csdl.ics.hawaii.edu/research/jupiter',
      Media: 'images/Jupiter.jpg',
    },
    {
      Date: '5/1/2009',
      Headline: 'Software ICU',
      Text: 'Shaoxuan Zhang completes M.S. research:  Learning Empirical Software Engineering Using Software Intensive Care Unit.',
      URL: 'http://csdl.ics.hawaii.edu/research/software-icu',
      Media: 'images/softwareicu.gif',
    },
    {
      Date: '6/1/2009',
      Headline: 'Google Summer of Code',
      Text: 'For the second year in a row, the Hackystat project was selected to participate in Google Summer of Code.',
      URL: 'http://csdl.ics.hawaii.edu/education/google-summer-of-code',
      Media: 'images/google-summer-of-code-logo.png',
    },
    {
      Date: '7/1/2009',
      Headline: 'WattDepot',
      Text: 'WattDepot supports development of enterprise level energy data collection and analysis.',
      URL: 'http://csdl.ics.hawaii.edu/research/wattdepot',
      Media: 'images/WattDepot.png',
    },
    {
      Date: '10/1/2011',
      Headline: 'Inaugural Kukui Cup',
      Text: 'After two years of preparation, the first Kukui Cup Energy Challenge begins.',
      URL: 'http://csdl.ics.hawaii.edu/research/kukui-cup',
      Media: 'images/kukuicup-logo.jpg',
    },
    {
      Date: '6/1/2012',
      Headline: 'Makahiki',
      Text: 'George Lee completes M.S. research: Makahiki: An extensible open-source platform for creating energy competitions.',
      URL: 'http://csdl.ics.hawaii.edu/research/makahiki',
      Media: 'images/makahiki-home-page.png',
    },
    {
      Date: '9/1/2012',
      Headline: '2012 Kukui Cup Challenges at UH, HPU, EWC',
      Text: 'The Kukui Cup expands to three campuses in 2012.',
      URL: 'http://csdl.ics.hawaii.edu/research/kukui-cup',
      Media: 'images/kc12-logo.png',
    },
    {
      Date: '5/1/2013',
      Headline: 'Kukui Cup',
      Text: 'Robert Brewer completes Ph.D. research: Fostering Sustained Energy Behavior Change And Increasing Energy Literacy In A Student Housing Energy Challenge',
      URL: 'http://csdl.ics.hawaii.edu/research/kukui-cup',
      Media: 'images/kukuicup-logo.jpg',
    },
    {
      Date: '10/28/2013',
      Headline: 'Brewer wins sustainability award',
      Text: 'Robert Brewer (Ph.D., Computer Science, 2013) has won the 2013 AASHE Graduate Student Research on Campus Sustainability Award.',
      URL: 'http://manoa.hawaii.edu/news/article.php?aId=6085',
      Media: 'images/img6085_3545.jpg',
    },
    {
      Date: '4/24/2014',
      Headline: 'Makahiki usability',
      Text: 'Jordan Takayama (B.S., Computer Science, 2014) completes undergraduate honors thesis on Makahiki system administration usability',
      URL: '',
      Media: 'images/jordan-takayama.jpg',
    },
    {
      Date: '1/16/2015',
      Headline: 'Software Trajectory Analysis',
      Text: 'Pavel Senin completes Ph.D. research: Software Trajectory Analysis: An empirically based method for automated software process discovery',
      URL: 'http://csdl.ics.hawaii.edu/research/software-trajectory-analysis/',
      Media: 'images/pavel-senin.jpg',
    },
    {
      Date: '7/16/2015',
      Headline: 'Makahiki and SGSEAM',
      Text: 'Yongwen Xu completes Ph.D. research: Makahiki and SGSEAM: Design and Evaluation of A Serious Game Framework for Sustainability and Stakeholder Experience Assessment Method',
      URL: 'http://csdl.ics.hawaii.edu/research/makahiki/',
      Media: 'images/yongwen-larger.jpg',
    },
    {
      Date: '3/3/2016',
      Headline: 'OPQ students win at Ideas Festival',
      Text: 'OPQ undergraduate researchers Rochelle Pagaduan and David Badke take second place in the student division at the Booz Allen Ideas Festival 2016',
      URL: 'http://www.boozallen.com/lp/booz-allen-ideas-festival-2016',
      Media: 'images/booz-allen-ideafest.png',
    },
    {
      Date: '8/1/2016',
      Headline: 'Burgess finishes M.S. thesis on acoustic sensing',
      Text: 'MANDE (the Maximal Acoustic Network Designer) takes advantage of high-resolution bathymetric data and advanced animal modeling to provide optimal network designs.',
      URL: 'http://csdl.ics.hawaii.edu/techreports/2016/16-04/16-04.pdf',
      Media: 'images/burgess.jpg',
    },
    {
      Date: '12/1/2016',
      Headline: 'New OPQ Box Design',
      Text: 'The Open Power Quality project has finished assembling engineering samples of its latest hardware design.',
      URL: 'http://openpowerquality.org/organization/news.html',
      Media: 'images/opqbox-feb-2019-square-closed.jpg',
    },
    {
      Date: '7/7/2017',
      Headline: 'Takayesu finishes M.S. thesis on RadGrad',
      Text: 'Amy Takayesu gathers baseline data to help determine the effectiveness of RadGrad.',
      URL: 'http://radgrad.org/organization/news.html#amy-takayesu-finishes-m.s.-thesis-on-radgrad',
      Media: 'images/amy.jpeg',
    },
    {
      Date: '2/8/2018',
      Headline: 'OPQ wins Presidents Green Award',
      Text: 'Open Power Quality wins a $10,000 prize for proposed work on agile power monitoring to support UH net zero goals.',
      URL: 'http://www.hawaii.edu/news/2018/02/12/2018-presidents-green-awards/',
      Media: 'images/green-awards-group.jpg',
    },
    {
      Date: '4/12/2018',
      Headline: 'Negrashov wins ARCS fellowship',
      Text: 'Serge Negrashov receives the 2018 Martin Award for Information and Computer Science from the ARCS Foundation.',
      URL: 'http://www.ics.hawaii.edu/2018/04/sergey-negrashov-receives-arcs-fellowship/',
      Media: 'images/serge.jpg',
    },
    {
      Date: '9/1/2018',
      Headline: 'NSF funds RadGrad',
      Text: 'NSF awards $300,000 to assess the impact of RadGrad on engagement, retention, and diversity.',
      URL: 'https://www.hawaii.edu/news/2018/09/04/computer-science-retention-grant/',
      Media: 'images/radgrad_logo.png',
    },
    {
      Date: '5/1/2019',
      Headline: 'Johnson receives teaching award',
      Text: 'Philip Johnson received the 2019 Board of Regents Medal for Excellence in Teaching.',
      URL: 'https://www.hawaii.edu/news/2019/05/13/bor-medal-for-excellence-2019/',
      Media: 'images/bor-medal.jpg',
    },
    {
      Date: '2/24/2020',
      Headline: 'Christe completes Ph.D. dissertation',
      Text: 'LAHA: A framework for adaptive optimization of distributed sensor frameworks.',
      URL: 'https://openpowerquality.org/blog/2020/02/24/anthony-dissertation.html',
      Media: 'images/christe.png',
    },
    {
      Date: '3/10/2020',
      Headline: 'Negrashov completes Ph.D. dissertation',
      Text: 'Design, Implementation, and Evaluation of Napali: A novel distributed sensor network for improved power quality monitoring.',
      URL: 'https://openpowerquality.org/blog/2020/03/10/serge-dissertation.html',
      Media: 'images/serge.jpg',
    },
  ].reverse();
}
