export default function getResearchData() {
  return [
    {
      Date: '1991 - 1994',
      Headline: 'CLARE',
      Text: 'Represent human learning of scientific literature to support useful computational manipulations.',
      URL: '',
      Media: 'images/clare-small.png',
    },
    {
      Date: '1993 - 1994',
      Headline: 'URN',
      Text: 'Explore representations and processes needed to model user interests and predict relevency of usenet postings.',
      URL: '',
      Media: 'images/urn-small.png',
    },
    {
      Date: '1994 - 1995',
      Headline: 'AEN',
      Text: 'Process and tool support for the development of high quality, jointly-authored hypertext documents.',
      URL: '',
      Media: 'images/aen-small.png',
    },
    {
      Date: '1991 - 1996',
      Headline: 'CSRS',
      Text: 'The Computer Supported Review System enables declarative definition of review processes and instrumentation for data collection.',
      URL: '',
      Media: 'images/csrs-small.png',
    },
    {
      Date: '1995 - 1996',
      Headline: 'Flashmail',
      Text: 'Investigate time-dependent electronic messages. One of the earliest "instant messaging" systems.',
      URL: '',
      Media: 'images/flashmail-small.png',
    },
    {
      Date: '1995 - 1996',
      Headline: 'HI-TIME',
      Text: 'Improve telecommunications policy through computer-mediated planning process.',
      URL: '',
      Media: 'images/hitime-small.png',
    },
    {
      Date: '1990 - 1996',
      Headline: 'Egret',
      Text: 'A framework providing tool support for the construction of computer-supported cooperative work applications.',
      URL: '',
      Media: 'images/egret-small.png',
    },
    {
      Date: '1998 - 1999',
      Headline: 'LOCC',
      Text: 'Grammar-based parsing and analysis for program size computation.',
      URL: '',
      Media: 'images/locc-small.png',
    },
    {
      Date: '1997 - 1998',
      Headline: 'JWiz',
      Text: 'Detect and analyze error types in Java programming to improve libraries, tools, and education.',
      URL: '',
      Media: 'images/jwiz-small.png',
    },
    {
      Date: '1996 - 1999',
      Headline: 'PSP Data Quality',
      Text: 'Experimental findings from Personal Software Process usage reveals significant errors due to manual data collection and analysis.',
      URL: '',
      Media: 'images/psp-data-quality-small.png',
    },
    {
      Date: '1997 - 2000',
      Headline: 'LEAP',
      Text: 'Lightweight, empirical, automated, and portable tools and techniques to support individual software process improvement.',
      URL: '',
      Media: 'images/leap-small.png',
    },
    {
      Date: '1999 - 2000',
      Headline: 'javaJAM',
      Text: 'Assist developers with reviewing software source, documentation, and comments.',
      URL: '',
      Media: 'images/javajam-small.png',
    },
    {
      Date: '1998 - 2000',
      Headline: 'MCS',
      Text: 'Mailing List Condensation is a system designed to strip out extraneous, conversational aspects of the data stream.',
      URL: '',
      Media: 'images/mcs-small.png',
    },
    {
      Date: '1999 - 2002',
      Headline: 'VCommerce',
      Text: 'An educational simulation game for teaching high-tech entrepreneurship.',
      URL: '',
      Media: 'images/vcommerce-small.png',
    },
    {
      Date: '2000 - 2002',
      Headline: 'Inca',
      Text: 'Design of an n-tier Enterprise JavaBean application for course approval request processing.',
      URL: '',
      Media: 'images/inca-small.png',
    },
    {
      Date: '2000 - 2002',
      Headline: 'TsunamiSim',
      Text: 'Use of GIS to overlay damages on relief efforts on disaster-afflicted regions.',
      URL: '',
      Media: 'images/tsunami-sim-small.png',
    },
    {
      Date: '2003 - 2004',
      Headline: 'CLEW',
      Text: 'The Collaborative Educational Website supports role-based editing and notifications.',
      URL: '',
      Media: 'images/clew-small.png',
    },
    {
      Date: '2004 - 2005',
      Headline: 'Priority Ranked Inspection',
      Text: 'How to prioritize inspection resources and apply them to areas of a system that need them most.',
      URL: '',
      Media: 'images/pri-small.png',
    },
    {
      Date: '2005 - 2006',
      Headline: 'Continuous GQM',
      Text: 'Integrate Hackystat real-time measurement with Goal-Question-Metric analysis.',
      URL: '',
      Media: 'images/continuous-gqm-small.png',
    },
    {
      Date: '2002 - 2006',
      Headline: 'JBlanket',
      Text: 'A new technique called "Extreme Coverage" for measuring test quality.',
      URL: '',
      Media: 'images/jblanket-small.png',
    },
    {
      Date: '2005 - 2008',
      Headline: 'SCLC',
      Text: 'Source Code Line Counter supports comment, non-comment, token and other counters for over 25 languages.',
      URL: '',
      Media: 'images/sclc-small.png',
    },
    {
      Date: '2005 - 2008',
      Headline: 'Jupiter',
      Text: 'Improve code review through an Eclipse plugin',
      URL: '',
      Media: 'images/jupiter-small.png',
    },
    {
      Date: '2003 - 2007',
      Headline: 'Zorro',
      Text: 'An automated method for detecting test-driven design practices.',
      URL: '',
      Media: 'images/zorro-small.png',
    },
    {
      Date: '2003 - 2007',
      Headline: 'Software Project Telemetry',
      Text: 'Track process and product metrics automatically through software sensors.',
      URL: '',
      Media: 'images/software-project-telemetry-small.png',
    },
    {
      Date: '2007 - 2009',
      Headline: 'Software ICU',
      Text: 'Rapidly assess the "health" of one or more projects. ',
      URL: '',
      Media: 'images/software-icu-small.png',
    },
    {
      Date: '2001 - 2011',
      Headline: 'Hackystat',
      Text: 'A framework for collection, analysis, visualization, interpretation, annotation, and dissemination of software development process and product data.',
      URL: '',
      Media: 'images/hackystat-small.png',
    },
    {
      Date: '2009 - 2014',
      Headline: 'Software Trajectory Analysis',
      Text: 'A data-mining framework for knowledge discovery from software processes artifacts. ',
      URL: 'http://code.google.com/p/hackystat-ui-trajectory/',
      Media: 'images/software-trajectory-analysis-small.png',
    },
    {
      Date: '2009 - 2014',
      Headline: 'Kukui Cup',
      Text: 'An energy challenge investigating energy literacy, conservation, and information technology.',
      URL: 'https://kukuicup.org/',
      Media: 'images/kukuicup-logo.jpg',
    },
    {
      Date: '2010 - 2015',
      Headline: 'Makahiki',
      Text: 'An open source serious game engine for sustainability.',
      URL: 'https://makahiki.readthedocs.io/en/latest/',
      Media: 'images/makahiki-image.png',
    },
    {
      Date: '2007 - 2015',
      Headline: 'WattDepot',
      Text: 'An open source, meter-agnostic RESTful web service for energy data storage, retrieval, and analysis. ',
      URL: 'http://wattdepot.org/',
      Media: 'images/WattDepot.png',
    },
    {
      Date: '2014 - present',
      Headline: 'Morea',
      Text: 'Generate educational websites organized by Modules, Outcomes, Readings, Experiences, and Assessments.',
      URL: 'http://morea-framework.github.io/',
      Media: 'images/morea-module.png',
    },
    {
      Date: '2013 - present',
      Headline: 'Open Power Quality',
      Text: 'Open source hardware and software for low-cost distributed power quality data collection, analysis, and visualization.',
      URL: 'https://openpowerquality.org/',
      Media: 'images/opqlogo.png',
    },
    {
      Date: '2015 - present',
      Headline: 'RadGrad',
      Text: 'Improve the undergraduate degree experience through increased engagement and retention.',
      URL: 'https://radgrad.org/',
      Media: 'images/radgrad_logo.png',
    },
  ].reverse();
}
