export default function getResearchData() {
  return [
    {
      date: '1991 - 1994',
      project: 'CLARE',
      text: 'Represent human learning of scientific literature to support useful computational manipulations.',
      url: '',
      media: 'images/clare-small.png',
    },
    {
      date: '1993 - 1994',
      project: 'URN',
      text: 'Explore representations and processes needed to model user interests and predict relevency of usenet postings.',
      url: '',
      media: 'images/urn-small.png',
    },
    {
      date: '1994 - 1995',
      project: 'AEN',
      text: 'Process and tool support for the development of high quality, jointly-authored hypertext documents.',
      url: '',
      media: 'images/aen-small.png',
    },
    {
      date: '1991 - 1996',
      project: 'CSRS',
      text: 'The Computer Supported Review System enables declarative definition of review processes and instrumentation for data collection.',
      url: '',
      media: 'images/csrs-small.png',
    },
    {
      date: '1995 - 1996',
      project: 'Flashmail',
      text: 'Investigate time-dependent electronic messages. One of the earliest "instant messaging" systems.',
      url: '',
      media: 'images/flashmail-small.png',
    },
    {
      date: '1995 - 1996',
      project: 'HI-TIME',
      text: 'Improve telecommunications policy through computer-mediated planning process.',
      url: '',
      media: 'images/hitime-small.png',
    },
    {
      date: '1990 - 1996',
      project: 'Egret',
      text: 'A framework providing tool support for the construction of computer-supported cooperative work applications.',
      url: '',
      media: 'images/egret-small.png',
    },
    {
      date: '1998 - 1999',
      project: 'LOCC',
      text: 'Grammar-based parsing and analysis for program size computation.',
      url: '',
      media: 'images/locc-small.png',
    },
    {
      date: '1997 - 1998',
      project: 'JWiz',
      text: 'Detect and analyze error types in Java programming to improve libraries, tools, and education.',
      url: '',
      media: 'images/jwiz-small.png',
    },
    {
      date: '1996 - 1999',
      project: 'PSP Data Quality',
      text: 'Experimental findings from Personal Software Process usage reveals significant errors due to manual data collection and analysis.',
      url: '',
      media: 'images/psp-data-quality-small.png',
    },
    {
      date: '1997 - 2000',
      project: 'LEAP',
      text: 'Lightweight, empirical, automated, and portable tools and techniques to support individual software process improvement.',
      url: '',
      media: 'images/leap-small.png',
    },
    {
      date: '1999 - 2000',
      project: 'javaJAM',
      text: 'Assist developers with reviewing software source, documentation, and comments.',
      url: '',
      media: 'images/javajam-small.png',
    },
    {
      date: '1998 - 2000',
      project: 'MCS',
      text: 'Mailing List Condensation is a system designed to strip out extraneous, conversational aspects of the data stream.',
      url: '',
      media: 'images/mcs-small.png',
    },
    {
      date: '1999 - 2002',
      project: 'VCommerce',
      text: 'An educational simulation game for teaching high-tech entrepreneurship.',
      url: '',
      media: 'images/vcommerce-small.png',
    },
    {
      date: '2000 - 2002',
      project: 'Inca',
      text: 'Design of an n-tier Enterprise JavaBean application for course approval request processing.',
      url: '',
      media: 'images/inca-small.png',
    },
    {
      date: '2000 - 2002',
      project: 'TsunamiSim',
      text: 'Use of GIS to overlay damages on relief efforts on disaster-afflicted regions.',
      url: '',
      media: 'images/tsunami-sim-small.png',
    },
    {
      date: '2003 - 2004',
      project: 'CLEW',
      text: 'The Collaborative Educational Website supports role-based editing and notifications.',
      url: '',
      media: 'images/clew-small.png',
    },
    {
      date: '2004 - 2005',
      project: 'Priority Ranked Inspection',
      text: 'How to prioritize inspection resources and apply them to areas of a system that need them most.',
      url: '',
      media: 'images/pri-small.png',
    },
    {
      date: '2005 - 2006',
      project: 'Continuous GQM',
      text: 'Integrate Hackystat real-time measurement with Goal-Question-Metric analysis.',
      url: '',
      media: 'images/continuous-gqm-small.png',
    },
    {
      date: '2002 - 2006',
      project: 'JBlanket',
      text: 'A new technique called "Extreme Coverage" for measuring test quality.',
      url: '',
      media: 'images/jblanket-small.png',
    },
    {
      date: '2005 - 2008',
      project: 'SCLC',
      text: 'Source Code Line Counter supports comment, non-comment, token and other counters for over 25 languages.',
      url: '',
      media: 'images/sclc-small.png',
    },
    {
      date: '2005 - 2008',
      project: 'Jupiter',
      text: 'Improve code review through an Eclipse plugin',
      url: '',
      media: 'images/jupiter-small.png',
    },
    {
      date: '2003 - 2007',
      project: 'Zorro',
      text: 'An automated method for detecting test-driven design practices.',
      url: '',
      media: 'images/zorro-small.png',
    },
    {
      date: '2003 - 2007',
      project: 'Software Project Telemetry',
      text: 'Track process and product metrics automatically through software sensors.',
      url: '',
      media: 'images/software-project-telemetry-small.png',
    },
    {
      date: '2007 - 2009',
      project: 'Software ICU',
      text: 'Rapidly assess the "health" of one or more projects. ',
      url: '',
      media: 'images/software-icu-small.png',
    },
    {
      date: '2001 - 2011',
      project: 'Hackystat',
      text: 'A framework for collection, analysis, visualization, interpretation, annotation, and dissemination of software development process and product data.',
      url: '',
      media: 'images/hackystat-small.png',
    },
    {
      date: '2009 - 2014',
      project: 'Software Trajectory Analysis',
      text: 'A data-mining framework for knowledge discovery from software processes artifacts. ',
      url: 'http://code.google.com/p/hackystat-ui-trajectory/',
      media: 'images/software-trajectory-analysis-small.png',
    },
    {
      date: '2009 - 2014',
      project: 'Kukui Cup',
      text: 'An energy challenge investigating energy literacy, conservation, and information technology.',
      url: 'https://kukuicup.org/',
      media: 'images/kukuicup-logo.jpg',
    },
    {
      date: '2010 - 2015',
      project: 'Makahiki',
      text: 'An open source serious game engine for sustainability.',
      url: 'https://makahiki.readthedocs.io/en/latest/',
      media: 'images/makahiki-image.png',
    },
    {
      date: '2007 - 2015',
      project: 'WattDepot',
      text: 'An open source, meter-agnostic RESTful web service for energy data storage, retrieval, and analysis. ',
      url: 'http://wattdepot.org/',
      media: 'images/WattDepot.png',
    },
    {
      date: '2014 - present',
      project: 'Morea',
      text: 'Generate educational websites organized by Modules, Outcomes, Readings, Experiences, and Assessments.',
      url: 'http://morea-framework.github.io/',
      media: 'images/morea-module.png',
    },
    {
      date: '2013 - present',
      project: 'Open Power Quality',
      text: 'Open source hardware and software for low-cost distributed power quality data collection, analysis, and visualization.',
      url: 'https://openpowerquality.org/',
      media: 'images/opqlogo.png',
    },
    {
      date: '2015 - present',
      project: 'RadGrad',
      text: 'Improve the undergraduate degree experience through increased engagement and retention.',
      url: 'https://radgrad.org/',
      media: 'images/radgrad_logo.png',
      bigImage: 'images/radgrad-big.png',
      // eslint-disable-next-line max-len
      longText: 'The fundamental goal of the RadGrad Project is to provide students, faculty, and advisors with an alternative perspective on the undergraduate degree program---which traditionally boils down to a single kind of activity (coursework) and a single metric for success (grade point average). Our alternative perspective is called the Degree Experience, and it gives first class status to both curricular activities (courses) and extracurricular activities (discipline-oriented events, activities, clubs, etc.) To establish the first class status of extracurricular activities, the Degree Experience perspective replaces GPA as the single metric for success with a three component metric called ICE that assesses student development with respect to Innovation, Competency, and Experience. Each student\'s Degree Experience also includes a representation of their disciplinary interests and career goals that helps them assess the relevance of potential curricular and extracurricular activities. Finally, the Degree Experience perspective is voluntary. It complements but does not change any existing undergraduate degree requirements of a university.',
    moreInfo: 'https://radgrad.org',
    },
  ].reverse();
}
